import { Veiculo, Manutencao } from './types';

export const INITIAL_VEHICLES: Veiculo[] = [
  {
    id: 'veic-1',
    placa: 'KWH4C00',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: '1318',
    ano: '10/10',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.2,
    capacidadeCarga: 13.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-2',
    placa: 'RKR4B10',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: 'ACCELO 1016',
    ano: '21/21',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -17.9,
    capacidadeCarga: 10.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-3',
    placa: 'RKO0E90',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: 'ACCELO 1016',
    ano: '19/20',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.1,
    capacidadeCarga: 10.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-4',
    placa: 'RKP3G20',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: 'ACELLO 1016',
    ano: '21/21',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.0,
    capacidadeCarga: 10.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-5',
    placa: 'LMD-3G81',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: 'ACCELO 815',
    ano: '14/14',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -17.8,
    capacidadeCarga: 8.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-6',
    placa: 'KPH1E01',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: '710',
    ano: '09/09',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.3,
    capacidadeCarga: 7.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-7',
    placa: 'LLO1H41',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: '710 PLUS',
    ano: '11/11',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.0,
    capacidadeCarga: 7.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-8',
    placa: 'LTW3I62',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: 'ATEGO 1719',
    ano: '19/20',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.1,
    capacidadeCarga: 17.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-9',
    placa: 'LLE5482',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: '1318',
    ano: '10/10',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -17.9,
    capacidadeCarga: 13.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-10',
    placa: 'LLT8C23',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: 'ACCELO 1016',
    ano: '12/12',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.2,
    capacidadeCarga: 10.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-11',
    placa: 'RKP3G13',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: 'ACCELO 1016',
    ano: '21/21',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.0,
    capacidadeCarga: 10.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-12',
    placa: 'SSD5A53',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: 'ACCELO 1017',
    ano: '24/25',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -17.8,
    capacidadeCarga: 10.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-13',
    placa: 'KZK2973',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: '1318',
    ano: '11/11',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.3,
    capacidadeCarga: 13.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-14',
    placa: 'KYN7D04',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: 'ACCELO 1016',
    ano: '12/12',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.1,
    capacidadeCarga: 10.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-15',
    placa: 'LSN3214',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: '1318',
    ano: '09/09',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -17.9,
    capacidadeCarga: 13.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-16',
    placa: 'KUX9664',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: '710',
    ano: '08/08',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.0,
    capacidadeCarga: 7.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-17',
    placa: 'SSD5A54',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: 'ACCELO 1017',
    ano: '24/25',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.2,
    capacidadeCarga: 10.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-18',
    placa: 'SRY7E54',
    marcaCaminhao: 'Kia',
    modelo: 'UK2500',
    ano: '24/25',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.1,
    capacidadeCarga: 2.5,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-19',
    placa: 'KQW2F05',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: 'ACCELO 815',
    ano: '12/12',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -17.8,
    capacidadeCarga: 8.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-20',
    placa: 'KYX6165',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: 'ATRON 1319',
    ano: '12/12',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.3,
    capacidadeCarga: 13.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-21',
    placa: 'LTZ3236',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: '710 PLUS',
    ano: '10/10',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.0,
    capacidadeCarga: 7.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-22',
    placa: 'RKT3C56',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: 'ACCELO 1016',
    ano: '20/21',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -17.9,
    capacidadeCarga: 10.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-23',
    placa: 'LOG1676',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: '1218',
    ano: '02/02',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.2,
    capacidadeCarga: 12.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-24',
    placa: 'RKF0E37',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: 'ACCELO 1016',
    ano: '19/20',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.0,
    capacidadeCarga: 10.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-25',
    placa: 'LSL3H28',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: '710',
    ano: '11/11',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.1,
    capacidadeCarga: 7.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-26',
    placa: 'RIX7D08',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: 'ACCELO 1016',
    ano: '21/21',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -17.8,
    capacidadeCarga: 10.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-27',
    placa: 'SRK3J29',
    marcaCaminhao: 'Kia',
    modelo: 'UK2500',
    ano: '23/24',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.2,
    capacidadeCarga: 2.5,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-28',
    placa: 'LLB6F99',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: 'ACCELO 915',
    ano: '09/09',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -18.0,
    capacidadeCarga: 9.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  },
  {
    id: 'veic-29',
    placa: 'RKV4A99',
    marcaCaminhao: 'Mercedes-Benz',
    modelo: 'ACCELO 1016',
    ano: '21/21',
    tipoRefrigeracao: 'Thermo King T-880R',
    temperaturaAlvo: -18,
    temperaturaAtual: -17.9,
    capacidadeCarga: 10.0,
    status: 'disponivel',
    statusRefrigeracao: 'ok',
    compressor: 'Sanden SD7H15',
    correia: 'PK 1090'
  }
];

// O localTime do sistema é 2026-06-20. Vamos iniciar o histórico limpo a pedido do usuário.
export const INITIAL_MAINTENANCES: Manutencao[] = [];
